### ISSUE TITLE
Offer additional .docx and .xslx export

### ISSUE THREAD

**Issue by AaronHarris** [sonnenkern/quip-export#13]
Hi Alexander,

First off, I want to commend you for this great repo. CLI is slick, tests are great, really well done!

Quip's automation API offers the ability to export threads to Documents and Spreadsheets: https://quip.com/dev/automation/documentation#export-document-to-docx 
Would it be possible to add this as a cli option to additionally exports documents as docx and spreadhseets as xlsx (in addition to the original .html)

**Comment by sonnenkern** [comment]
Hi @AaronHarris, I've added new option '--docx' in version 2.2.0. The details you can find in Readme. Could you try the new version and tell me if it works for you. Thnx.
