### ISSUE TITLE
What content is exported?

### ISSUE THREAD

**Issue by cathyb-sf** [sonnenkern/quip-export#31]
Hi! When someone generates a personal access token, what content is actually exported?
Is it an export of the entire site?
Is it an export of docs owned by the person? 
Is it an export of the personal folder?
Is it an export of docs the person was a full access member of? 

Thanks!
Cathy

**Comment by sonnenkern** [comment]
Hi! The Quip-Export Tool exports only Private, Shared and Group folders that you have read-access to from your account. That means all folders and files, what you can see, when you sign in your Quip-Account. The Quip-Token is just kind of credentials to get API access to your account.
