### ISSUE TITLE
Subfolder token

### ISSUE THREAD

**Issue by bz-cwt** [sonnenkern/quip-export#6]
With https://quip.com/api/personal-token, it seems that it can only download the documents in the root folder, do you know how to get the token for the subfolders?

**Comment by sonnenkern** [comment]
There is no possibility to get Access Token to dedicated folders. Quip API Access Token (also called Personal Access Token) gives your access to your whole Quip account. Quip-Export exports recursively all available in the account folders (private folder, shared folder and group folder) with all subfolders. If you need only one certain folder, you can export all folders in your Quip-account in a standard way, and then just find the folder, what you are interesting in. Could it solve your problem? 

Which kind of Quip-Export tool are you using? Is it web version, node version or npm module in your app? Actually, there is a possibility to export certain folders quite easy, but this possibility currently available only if you are using quip-export npm module in your own app. Maybe in the future I will add the folders selection to the user interface of web-version and node-version.

**Comment by bz-cwt** [comment]
@sonnenkern I am using your tool here in this github repo. Maybe I missed something, but it does not really export the folder documents recursively, but only the ones which are not in the folders.

**Comment by sonnenkern** [comment]
1. What command do you use to start the tool:
   - npx quip-export [options]?
   - quip-export [options]?
   - node quip-export [options]?
2. Do you have some exceptions or errors in the console? 
3. Could you try to run the app with --debug flag, and look after at log-file?

**Comment by josemdv** [comment]
I'm having the exact same issue, it doesn't export folders (or subfolders) recursively. To answer your previous questions, I'm using the following command:

"node quip-export -t "xxx" -d /Users/xxx/QuipExport --embedded-styles --embedded-images --debug"

This is the output of the command above:

```
[01-05-2020 16:30:35.003] DEBUG: HTTP 503: for /blob/TAAA5lXK/g6sGAE2a-6e29Z-Cg, waiting in ms: 24997
[01-05-2020 16:31:06.146] DEBUG: Couldn't fetch /folders/?ids=RNCARcYyc,DSYA3tTC,RaOASIwHM, received 403
[01-05-2020 16:31:06.147] ERROR: Can't load the Child-Folders for Folder: xxxx Documents/
[01-05-2020 16:31:06.148] DEBUG:
    query_count: 145
    getThread_count: 0
    getThreads_count: 4
    getFolder_count: 0
    getFolders_count: 5
    getBlob_count: 118
    getPdf_count: 0
    getXlsx_count: 0
    getUser_count: 1
```

**Comment by sonnenkern** [comment]
@josemdv 
Oh, thank you a lot for debug information. You seem to have some restricted folders in your account. I didn't have any in my account, so I couldn't know about the issue. The restricted folders aren't documented in official documentation to Quip Automation API as well. Now it should work correctly, all restricted folders will be just omitted, and you can see the note about it in log file after export (sure in debug mode). I've published the new version of Quip-Export tool 1.10.1. Could you try it and check whether it works for you.

**Comment by sonnenkern** [comment]
@bz-cwt 
Hi, I think you have also some restricted folders in your account, and my tool wasn't work correctly with this kind of folders. I've solved the problem in version 1.10.1. Could you please try it and tell me whether it works for you or not. Thnx!

**Comment by bz-cwt** [comment]
@sonnenkern Indeed I have some restricted folders, and currently I am able to download the subfolders which I have access to. Thanks.

**Comment by josemdv** [comment]
Awesome! It now works as expected!
